on:
   push:
     branches:
       - main

name: release-please

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      frontend-release: ${{ steps.release.outputs.frontend--release_created }}
      frontend-major: ${{ steps.release.outputs.frontend--major }}
      frontend-minor: ${{ steps.release.outputs.frontend--minor }}
      frontend-patch: ${{ steps.release.outputs.frontend--patch }}
      backend-release: ${{ steps.release.outputs.backend--release_created }}
      backend-major: ${{ steps.release.outputs.backend--major }}
      backend-minor: ${{ steps.release.outputs.backend--minor }}
      backend-patch: ${{ steps.release.outputs.backend--patch }}
      core-release: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: manifest

  build-frontend:
    runs-on: ubuntu-latest    
    needs: release-please
    permissions:
      contents: read
      packages: write
    if: ${{ needs.release-please.outputs.frontend-release }}
    steps:
      - uses: actions/checkout@v3

      - name: Log into github docker
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend
          tags: |
            type=semver,pattern={{version}},value=v${{ needs.release-please.outputs.frontend-major }}.${{ needs.release-please.outputs.frontend-minor }}.${{ needs.release-please.outputs.frontend-patch }}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Extract metadata for Docker
        id: meta2
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend-enterprise
          tags: |
            type=semver,pattern={{version}},value=v${{ needs.release-please.outputs.frontend-major }}.${{ needs.release-please.outputs.frontend-minor }}.${{ needs.release-please.outputs.frontend-patch }}
            type=sha

      - name: Build and push Docker image (enterprise)
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta2.outputs.tags }}
          labels: ${{ steps.meta2.outputs.labels }}
          build-args: |
            BUILD_VERSION=enterprise

  build-backend:
    runs-on: ubuntu-latest
    needs: release-please
    permissions:
      contents: read
      packages: write
    if: ${{ needs.release-please.outputs.backend-release }}
    steps:
      - uses: actions/checkout@v3

      - name: Log into github docker
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend
          tags: |
            type=semver,pattern={{version}},value=v${{ needs.release-please.outputs.backend-major }}.${{ needs.release-please.outputs.backend-minor }}.${{ needs.release-please.outputs.backend-patch }}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
